version: '3.8'

services:
  quickshow:
    container_name: quickshow-client
    image: quickshow:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /quickshow/client
    volumes:
      - ./client:/quickshow/client
      - /quickshow/client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
